### ISSUE TITLE
Native Events (Replacement for NWNX events)

### ISSUE THREAD

**Issue by Jorteck** [nwn-dotnet/Anvil#184]
Please post which events you are currently using so we can focus on migrating them first :)

The full list:
- [x] AssociateEvents
- [x] BarterEvents
- [x] CalenderEvents
- [x] ClientEvents
- [x] CombatEvents
- [ ] DebugEvents
- [ ] DMActionEvents
- [ ] EffectEvents
- [x] ExamineEvents
- [ ] FactionEvents
- [x] FeatEvents
- [x] HealingEvents
- [ ] InputEvents
- [x] InventoryEvents
- [x] ItemEvents
- [ ] JournalEvents
- [x] LevelEvents
- [ ] MapEvents
- [ ] MaterialChangeEvents
- [ ] ObjectEvents
- [x] PartyEvents
- [ ] PlymorphEvents
- [ ] PVPEvents
- [ ] QuickbarEvents
- [ ] QuickChatEvents
- [ ] ResourceEvents
- [ ] SkillEvents
- [x] SpellEvents
- [x] StealthEvents
- [x] StoreEvents
- [ ] TimingBarEvents
- [ ] TrapEvents
- [ ] UUIDEvents

**Comment by milliorn** [comment]
- FeatUseEvents
- ExamineEvents
- SpellEvents
- PlaceableEvents
- BarterEvents
- StealthEvents
- StoreEvents
- CombatEvents

Those are Events I'm already using.

**Comment by Chimerik** [comment]
- Attack and Damage events (DamagePlugin)
- Chat events (ChatPlugin)
- CombatEvents (on_start_combat_round and on_combat_mode)
- DmActionsEvents
- DetectionEvents (on_do_listen_detection)
- ELCEvents
- ExamineEvent
- FeatEvents
- ItemEvents (including item scroll learn)
- InputEvents (on_input_toogle_pause_before and on_input_emote)
- JournalEvents
- LevelEvents
- MapPinEvents
- PartyEvents
- SkillEvents
- SpellEvents
- StealthEvents
- StoreEvents
- TimingBarEvents

(What "PvPEvents" and "ObjectEvents" are you refering to?)

**Comment by Mefi100** [comment]
ELC and Examine events currently

**Comment by jakkn** [comment]
- StoreEvents
- PartyEvents

**Comment by Jorteck** [comment]
Since the system for adding native events has been implemented, as well as a fair chunk of the existing NWNX events, I'm closing this issue. Please make individual issues for any events that are still missing, but you would like to use in your plugin/project.
