### ISSUE TITLE
GetFamiliarCreatureType

### ISSUE THREAD

**Issue by milliorn** [nwn-dotnet/Anvil#44]
`GetFamiliarCreatureType` function needs to be tested.  This should be tested to see if it works on non-player characters.  Currently it is only known that this works on playable characters.  
```cs
    public FamiliarCreatureType FamiliarType
      => (FamiliarCreatureType)NWScript.GetFamiliarCreatureType(this);
```
This currently lives in `src/main/NWN/API/Object/NwCreature.cs`

**Comment by Jorteck** [comment]
Fixed with https://github.com/nwn-dotnet/Anvil/pull/261
