### ISSUE TITLE
Missing NUnit package references

### ISSUE THREAD

**Issue by jakkn** [nwn-dotnet/Anvil#452]
NUnit appears to be missing from `NWN.Anvil.TestRunner/NWN.Anvil.TestRunner.csproj`

```log
/home/jkn/dev/Anvil/NWN.Anvil.TestRunner/src/main/TestRunnerService.cs(12,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?) [/home/jkn/dev/Anvil/NWN.Anvil.TestRunner/NWN.Anvil.TestRunner.csproj]
/home/jkn/dev/Anvil/NWN.Anvil.TestRunner/src/main/TestRunnerService.cs(13,7): error CS0246: The type or namespace name 'NUnitLite' could not be found (are you missing a using directive or an assembly reference?) [/home/jkn/dev/Anvil/NWN.Anvil.TestRunner/NWN.Anvil.TestRunner.csproj]
```
Are these the correct versions?
```
dotnet add NWN.Anvil.TestRunner/ package NUnit --version 3.13.2
dotnet add NWN.Anvil.TestRunner/ package NUnitLite --version 3.13.2
```

After installing I get another error from https://github.com/nwn-dotnet/Anvil/blob/adaf95247ea27c96c53c7d92899bc4e97d480f8b/NWN.Anvil.TestRunner/src/main/TestRunnerService.cs#L48
```
'TestCommand' does not contain a definition for 'DefaultSynchronizationContext' [NWN.Anvil.TestRunner]csharp(CS0117)
```

**Comment by Jorteck** [comment]
The test runner uses a customised version of the package: https://github.com/nwn-dotnet/nunit
Did you pull all submodules? You should use the nunit attributes included in the test runner package rather than the ones from the nuget package: https://github.com/nwn-dotnet/Anvil/tree/development/NWN.Anvil.TestRunner/src/lib

**Comment by jakkn** [comment]
Oh I didn't realize there are submodules now. Closing.
