### ISSUE TITLE
Issue - NwCreature.AlwaysWalk - Behaviour not applied after logging out

### ISSUE THREAD

**Issue by Chimerik** [nwn-dotnet/Anvil#480]
The behaviour of NwCreature.AlwaysWalk = true is not applied if the player character logs out and relogs in later.

**Comment by Jorteck** [comment]
I remembered why this was made non-persistent, I just forgot to update the docs.

It's a "Lazy" service, meaning it won't hook the needed engine functions until the API is used for the first time.

This is to get the benefits that NWNX has with their plugin approach as you don't pay for the overhead for features & APIs you are not using. It's only when you decide to apply the AlwaysWalk behaviour that the hooks are added.
